### ISSUE TITLE
Hiring a project manager

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#10]
Lots of our tasks are blocked on the limited administrative time that the volunteer board members can contribute. We're looking to hire an experienced project manager to help facilitate. See the job description below (approved by the foundation board):

The Zcash Foundation is seeking to hire a Senior Project Manager to help with the Foundation.
 ======
The Zcash Foundation is a non-profit organization, tasked with supporting privacy-preserving cryptocurrencies and public blockchains.
 
Responsibilities:
------
- Coordinating with volunteers and board members
   The bottleneck right now is attention and cycles from the board, who are excellent and have good ideas, but are full time engineers, researchers, etc. There are also many folks who would be interested in volunteering, but lack the attention to steer and recognize them. We need someone to “push” in order to bring out the best in us.
 
- Project management
   Our projects include:
    - Organization of community-building events focused on privacy-preserving cryptocurrencies
    - Grant programs and bounty program to support community-driven projects
    - Education of non-profit organizations on the use of Zcash to receive private donations
    - Community involvement, polling, and communication platforms
 
- Hire and manage professional services as necessary
    - Legal and accounting in order to comply with expectations of a non-profit
    - Custody of virtual currencies received as donations
 
    - Communicating with the public via blog posts, website
	Zcash Foundation needs to be a thoroughly *transparent* organization. We’re accountable to the public, who have an interest in understanding how our donations are spent and how our decisions are made.
 
More details:
----
### Expected workload
Part time, 10-20 hours per week
Potential to scale to full-time position in 6-12 months
 
### Compensation
Depending on location and experience, compensation will be $25/hr-$40/hr.
 
How to apply
----
Send email to Andrew Miller socrates1024@gmail.com
Preference given to candidates located in US

**Comment by zancas** [comment]
Perhaps it would help align incentives if the manager were explicitly compensated in zcash?

**Comment by asm13243546** [comment]
* Custody of virtual currencies received as donations

How does this work exactly?

**Comment by mineZcash** [comment]
@asm13243546 I would suggest applying to Andrew about the position before asking about financial custody details.

**Comment by asm13243546** [comment]
Lol just nosy.

**Comment by asm13243546** [comment]
But have done so, pursuant your advice.

**Comment by asm13243546** [comment]
Rereading. <Buries head in book.>

**Comment by asm13243546** [comment]
Just to clarify but at risk of over-comment,

Hire and manage professional services as necessary

is the parent directive of

Custody of virtual currencies received as donations

and I'm new to your community, so I was wondering if something public had already been established, since, if not, it becomes something of a work item for whatever PM.

Hopefully that's clear enough.

**Comment by zancas** [comment]
Is there an intention to hire other specialists...   e.g. a marketing/publicist/media-content generator?

**Comment by amiller** [comment]
We've hired Josh Cincinnati as the program manager, starting aug 14
http://z.cash.foundation//blog/welcome-josh/
