### ISSUE TITLE
Better PR for visibility

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#12]
Presumably no one knows what we are doing. 
See also this tweet https://twitter.com/ZancasDeArana/status/879714852746518529

Although we discharge our "transparency" needs primarily by putting things on our GitHub and public chat, this doesn't reach all viewers. 

Maybe this is something the Senior project manager will help with. More frequent blog posts or more frequent status updates to the website?

Volunteers could propogate more information too.

**Comment by zancas** [comment]
Github is a great (and probably in many ways "correct") first step towards letting people know about the Foundation, but it bears mentioning that most humans don't use github.
  Maybe there's sufficient conciousness/awareness raising work to do that the Foundation should hire a PR specialist in addition to the manager?   Or maybe the manager should evaluate the costs and benefits of hiring such an individual?    My vague impression is that there's more work than the Foundation currently has staff for.

**Comment by amiller** [comment]
We're taking elsewhere about having a monthly newsletter organized in part around working groups. This would serve that purpose.

**Comment by acityinohio** [comment]
Considering this and #53 closed with @sonyamann hired.
