### ISSUE TITLE
Compensated Use Case/Wishlist Surveys

### ISSUE THREAD

**Issue by zancas** [ZcashFoundation/ZcashFoundation#13]
To improve our understanding of how zcash is used, and what features people might want, The Foundation could distribute surveys combined with an incentive contract whereby respondents are compensated with a small payment of ZEC for their data.

**Comment by zancas** [comment]
There are several things we can do to control for bot-created content.

1.  Require respondents to solve a set of CAPTCHA challenges.

2.   Offer a subset of surveys that require the recipient address to be verified.

     Option 2. presents an interesting set of trade-offs.   For concreteness I propose that the Foundation partner with, and compensate a crypto currency exchange that already has infrastructure in place.   (e.g. https://kraken.com)...  (Work In Progress)

**Comment by acityinohio** [comment]
Closing this as part of ZcF GitHub Issues cleanup.
