### ISSUE TITLE
Support for Tor servers

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#14]
In my opinion it would be a critical failure for the privacy if the number of Tor reachable Zcash nodes drops too low. 

Right now I know of only one project hosting zcash node hidden services. They rely on funding month by month, basically. If it elapses the hosts will shut down.
https://forum.z.cash/t/zcash-on-tor-a-community-funded-proposal/14651/17

We need a project to fund these. I think this is critical enough to fund even outside the grant program.

**Comment by acityinohio** [comment]
This was awarded as part of this grant cycle, so I'm closing this out: https://github.com/ZcashFoundation/GrantProposals-2017Q4/issues/11
