### ISSUE TITLE
Community Web Infrastructure 

### ISSUE THREAD

**Issue by mineZcash** [ZcashFoundation/ZcashFoundation#15]
Proposal for Foundation support of Zcash community resource infrastructure.

With the October launch of Zcash the development team has made great strides in improving the Zcash protocol and the Zcash promise of true financial privacy has attracted thousands of new Zcash users. For community members such as myself and radix42 there has been a significant increase  in traffic to three key areas. 

The Zcash community website visitors
The Zcash community rocket chat users
The zcash4win & zcash4mac downloads and proving keys

Initially when the community was smaller it was not a big deal for radix42 and myself to host these resources as our way of giving back and helping contribute to the success of Zcash and what it stands for. This exponential growth of the use resources has necessitated more robust servers, hosting and bandwidth. 
My out-of-pocket expenses and traffic can be seen in this chart: [Here](https://www.zcashcommunity.com/zcommunityexpenses2017/) I have already submitted this information to Andrew privately for possibly consideration but to promote transparency I have decided that it is not a big deal to have these details made public. My costs are not huge since I do most of the work myself, but seeing as I have a Son starting college this September, they are not insignificant.  

I was speaking with radix42 who has just recently decided he will have to discontinue hosting the Zcash proving keys due to a huge shift in downloads since being more prominently featured for his zcash4win and zcash4mac software on the zcashcommunity wallets page. This has resulted in a unexpected CloudFront bill of over $1,200.00 for Zcash software downloads in the last 30 days. 

As Zcash continues to grow and the Zcash Company continues to focus on the core needs of the Zcash software and protocol it is my hope that the Foundation would be able to help offset some of the basic expenses so that they do not eventually balloon beyond what is feasible. 

Thank you for your consideration and I welcome any feedback on this issue.

P.S. I'm not sure if this should be added to the grant proposal issue https://github.com/ZcashFoundation/ZcashFoundation/issues/2
opened by @tromer

**Comment by radix42** [comment]
Well, I'm not going to take down my proving key mirror, I'm just going to flip the embedded download url for it in zcash4win's next release back to the url for the ZcashCo copy, which is hosted on amazon s3 rather than CloudFront. Which means I"ll get more support tickets about "hey it keeps not finishing the proving key" from my users, but I'll just bite that bullet. @zooko if you guys added a CloudFront distribution point in front of your s3 URL it would help out EVERYONE a lot!

**Comment by radix42** [comment]
or maybe the foundation could setup such a CDN-based download service for proving keys for the entire zcash-ecosystem?

**Comment by radix42** [comment]
that's what I've essentially done by dropping my mirror's URL into the non-linux builds of all the zcash forks I've worked on, made it tolerable to download the thing. I can track how many client downloads I have by coin, and the non-zcash forks are just noise in the amount of downloads compared to zcash4win clients

**Comment by radix42** [comment]
The problems of success! My recent AWS bills (just for bandwidth, I have my ec2 all separately billed...and on that last month less that $50 was non-zcash forks)
![screen shot 2017-07-03 at 4 55 06 pm](https://user-images.githubusercontent.com/6250192/27810565-d2732770-6010-11e7-877a-8bc14ddec057.png)

**Comment by radix42** [comment]
PS if the Foundation does decide to pay for ongoing hosting of proving keys on a high quality CDN, I'd be more than happy to donate the labor to setting that all up if you do it on AWS CloudFront.

**Comment by mineZcash** [comment]
I was able to integrate two additional languages (Spanish and Portuguese) on the main pages of Zcashcommunity thanks to a community member who translated the pages. It would be nice to have even more languages supported, Zcash Company has incoporated the use of Transifex (multilingual translation company) I think it would be good to have a resource for the community site as well.

**Comment by mineZcash** [comment]
Related to #24

**Comment by mineZcash** [comment]
I am closing this issue since it has been submitted as a Grant Proposal https://github.com/ZcashFoundation/GrantProposals-2017Q4/issues/5
