### ISSUE TITLE
Onboarding for newcomers who want to contribute or volunteer to development/technical

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#18]
Suppose a volunteer shows up and wants to help with Zcash. What resources can we point them to? 

For open source development, the usual answer is to read the posts on a development mailing list and look for opportunities, or to look for github tickets that might be fun. Certainly https://github.com/zcash/zcash/issues seems to be full of good ideas. Is there anything we can do to help new people participate in development? 

What about triaging some tickets as being approachable with limited experience? This would go along well with a bounty program, where funds are allocated to sponsor development tasks. 

Another idea is development guides, catered towards newcomers to the Zcash community but with experience in Bitcoin, or experience in general development, etc.

The grant proposal program #2 seems like a great way for established developers / project leaders to get funding for something they want to do, but that is a higher bar than for a newcomer with casual/uncertain interest.

**Comment by acityinohio** [comment]
Closing this out for now, but I think the spirit here will be present in the web redesign/materials associated with it (cc @sonyamann).
