### ISSUE TITLE
Link here from the website.

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/ZcashFoundation#19]
People (such as @zookozcash) complained they can't find this information from the https://z.cash.foundation website. Let's fix that!

**Comment by diracdeltas** [comment]
Do you mean this github repo? Or the issues page of this github repo?

**Comment by amiller** [comment]
I put a preliminary link to the repository in the nav bar of the website. I'm considering that enough to close this, though better integration will be part of the website update.
