### ISSUE TITLE
list of working groups and their status

### ISSUE THREAD

**Issue by zookozcash** [ZcashFoundation/ZcashFoundation#20]
I want to see a table of existing or proposed working groups, their status, and their coordinator. "Status" would include "proposed", "needs a coordinator", "approved by the Foundation", "active". Also I'd like there to be a link I can follow to check for recent activity, i.e. a github issue tracker sorted by most recently changed ticket, or a mailing list showing most recent posts, or a blog, or something.

`
Working Group | Coordinator | Status | Link to Documentation | Link to Recent Activity
------------------------------------------------------------------------------------------------------------------
Nonprofits | Paige Peterson | Active | https://github.com/ZcashFoundation/ZcashFoundation/blob/master/WorkingGroups/NonProfits.md | https://chat.zcashcommunity.com/channel/the-zcash-foundation
… | … | … | … | …
`

**Comment by acityinohio** [comment]
Closing this as part of ZcF GitHub Issues cleanup.
