### ISSUE TITLE
fund bounties/awards/consultants to analyze candidate crypto algorithms for Sapling

### ISSUE THREAD

**Issue by zookozcash** [ZcashFoundation/ZcashFoundation#21]
The Zcash New Crypto Analysis Project
-----------------------------------------------------

New crypto things that need analysis, because we are considering using them in Sapling, and they are not yet super-well-studied by lots and lots of cryptographers:
 * Groth-2016 proving system (can there be a security reduction (“security proof”) of Groth-2016 that isn't in the Generic Group Model?)
 * MiMC and specific parameters/choices (https://github.com/zcash/zcash/issues/2233#issuecomment-291840857)
 * BLS12-381
 * the other curve (?? I don't even understand what this is. @ebfull?) that comes with BLS12-381

Kinds of analysis we could solicit:
 * Prizes (paid in ZEC) for breaking reduced-round versions of MiMC broken
 * Prizes (ZEC) for best analysis paper
 * Hiring a specific consultant and asking them to write an analysis of one of these (and then another cryptographer to analyze the next one, etc.)

This is urgent because within the Sapling development process we are currently _committing_ to using (or not-using) certain ones of these.

**Comment by ebfull** [comment]
> the other curve (?? I don't even understand what this is. @ebfull?) that comes with BLS12-381

This other curve is the "embedded curve" that is efficient to use inside the zk-SNARK. I've proposed a curve [here](https://github.com/zcash/zcash/issues/2230#issuecomment-317182190) but I'm not totally committed to that particular curve. There could be better ones.

**Comment by arielgabizon** [comment]
Hi,
At zdep I said I think hiring is better than a prize.
I still think so for the curve.
But for Groth-2016, I would be comfortable describing the project and
judging who should get the reward.
The project description can be something like "Show an attack against
Groth-2016 or prove it, or a variant of it where the prover complexity
doesn't change, secure under weaker assumptions"


Here is a possible description:

Bounty for ZK-SNARK research:
------------------------------------------- 


Zcash will most likely use the zk-SNARK designed by Jens Groth in his 2016 paper 'On the Size of Pairing-based Non-interactive Arguments' in a future version of its software. Motivated by this, the Zcash foundation will give 30,000$ worth of ZEC to the authors of a research paper that it will judge as best, in one of the following themes:

 -   Give a security proof of the Groth16 SNARK, or a variant of it with very similar proof length and prover complexity, under weaker assumptions/in a weaker model than the Generic Group Model

 -  Indicate a weakness in the Groth16 SNARK, or in relevant cryptographic assumptions implied by the Generic Group Model, e.g., the d-power Knowlege of Exponent Assumption and the other assumptions decsribed in Appendx A of [PHGR16]. 




[PHGR16]-Bryan Parno, Jon Howell, Craig Gentry and Mariana Raykova -
	 Pinocchio: Nearly Practical Verifiable Computation

**Comment by zmanian** [comment]
Prizes are more effective when the population of qualified researchers is large.

For this kind of cryptanalysis, the population of qualified researchers is small and the review committee should be able to evaluate both traditional and nontraditional researchers.

It would be a very valuable to get a qualified person to devote attention to these bits of novel cryptography.

**Comment by zmanian** [comment]
It's sort of interesting question weigh priorities between infrastructure for safely doing hard forks and evaluating the safety of the new cryptographic components that will be introduced in a hard fork.

**Comment by amiller** [comment]
I'd love it if someone submits a  and submitting it as a proposal to the grant program?

**Comment by amiller** [comment]
I'd love it if someone submits a  and submitting it as a proposal to the grant program?

**Comment by amiller** [comment]
Here's an actionable idea evolved from chatting with Matt Green and Eran Tromer. We should use the output of the zApps working group as a way of catalyzing researcher interest in these protocols. The zApps working group (among other things, such as the ZSL & Quorum) shows the significant demand for zksnark protocols, and therefore effort invested in cryptanalysis is worthwhile.

So here are the steps:
1. Make a list of cryptographers who we'd especially like to reach
2. Write a summary of the discussion/activity in the zApps WG @acityinohio that is targetted towards these cryptographers, showing the interest. Share it with them
3. Ask the cryptographers to participate in the WG by giving a short hangout talk?
4. Organize an informal conference inviting cryptographers at one of their host universities (I would push the foundation to sponsor it)

One possible outcome of this could be catalyzing a new academic conference (a workshop attached to a security/crypto conference?) focusing on zk protocols with applictation to cryptocurrencies.

**Comment by amiller** [comment]
We've had the first zApps WG meeting, and are now pending on the establishment of an email mailing list #38, and then we can send an update of the working group hangout.

**Comment by daira** [comment]
#38 says it's done; what's the progress on this ticket?

**Comment by amiller** [comment]
Good point, thanks for reminding about this ticket! We have a mailing list, https://lists.z.cash.foundation/mailman/listinfo/zapps-wg I need to write a thank-you and recap of the initial hangout and then also finish the follow-up I'm thinking of about the low-tech way of practicing with the sustainable snark setup procedure

**Comment by khovratovich** [comment]
I would be interested to participate in such research, in particular on hash functions.

**Comment by acityinohio** [comment]
Closing this as part of ZcF GitHub Issues cleanup
