### ISSUE TITLE
invalid SSL cert on https://z.cash.foundation/

### ISSUE THREAD

**Issue by diracdeltas** [ZcashFoundation/ZcashFoundation#22]
Ironically, for a privacy-focused project, our website has an invalid SSL cert (CN github.com) :(. 

As far as I know, the only easy way to get around this is to use Cloudflare's "Universal SSL" service. https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by amiller** [comment]
Eventually I'd like to move off GitHub-pages for this given the lack of https support. Using cloudflare seems like an alright compromise.

**Comment by amiller** [comment]
I tinkered with it, got it routed through cloudflare, but now the build is broken. I probably need help with it.

**Comment by amiller** [comment]
Cloudflare https is now working! :1st_place_medal:
