### ISSUE TITLE
Fund a bug bounty program

### ISSUE THREAD

**Issue by SergioDemianLerner** [ZcashFoundation/ZcashFoundation#23]
Because hackers are your friends.

**Comment by amiller** [comment]
Thoughts on how much is appropriate? Or on who handles the evaluation?
Ethereum bug bounty program is pretty good I think.

**Comment by diracdeltas** [comment]
The hard part is scoping, aka what bugs are eligible for bounty. Depending on scope, this may be a better issue for Zcash company instead of Zcash foundation.

**Comment by amiller** [comment]
We could have a working group whose iob is define the scope, make relative funding decisions, and evaluate the reports. It seems like something that's in scope for the Foundation and would also be a good collaboration with the Zcash Company.

**Comment by nathan-at-least** [comment]
I'd like to see a scope larger than ZcashCo produced products, including for example other implementations, open source mobile and hardware wallets, key management tools, and MPC software.

I suspect the trick to a good bug bounty program is getting someone with good expertise and experience to operate it. Paging @diracdeltas, do you have advice for this request?

**Comment by tromer** [comment]
Enlarging the scope to code well outside the control/review/knowledge of the Foundation makes sense, but raise some questions:
- Variable code quality: it makes more sense to award large bounties to stable well-reviewed code (e.g., zcashd) than little-known new projects
- Importance of the vulnerable product
- Conflict of interest /  manipulation

The generic way to handle all of these is to not commit to particular amounts, but rather give an indication on the order of magnitude (e.g., "the Foundation reserves $X for bounties in 2018"), state the evaluation criteria, and form a committee to apply them at its discretion.

**Comment by acityinohio** [comment]
Closing this as part of ZcF GitHub Issues cleanup.
