### ISSUE TITLE
Translate Website to Spanish, Brazilian, etc. Hire content creators

### ISSUE THREAD

**Issue by Codnova** [ZcashFoundation/ZcashFoundation#24]
It will be nice if the website/documentation is translated into other languages such as Spanish, Brazilian,  French, German, Russian. Thus increasing user and developer's engagement reach. 
Our cryptocurrency community is becoming increasingly diverse, an effective communication strategy is needed to spread the word on Zcash and Blockchain technology, especially given the steep learning curve Zcash tech has. I propose to the foundation/company the support full time/part time community manager, and copywriter, to engage with the users and the community.

**Comment by zancas** [comment]
I am +1 on this issue.   I think it would be ideal to hire translators/content creators in diverse communities/geographies.

**Comment by amiller** [comment]
Here's a pull request from Javier Mardones to form a working group specifically for Translations. #27

**Comment by amiller** [comment]
Javier Mardones has completed one instance of a translation, but we have no where to integrate it. 
To close this issue, we also need to figure out how to add jekyll posts in language translations, and have them in the site work ok somehow.

**Comment by amiller** [comment]
We've now added portugues translation links to each blog post, in a cursory way (links to just unformatted text in the issues).

We can close this issue once the Translations Working group defines a process that can reliably handle translations for other languages as well.

**Comment by zancas** [comment]
Perhaps now would be an opportune moment to publish some Mandarin translations?

**Comment by tloriato** [comment]
I'd be glad to provide portuguese (pt-br) translation for the Foundation!

@javiermardoness shoot me an email!

**Comment by acityinohio** [comment]
Closing this as part of ZcF GitHub Issues cleanup.

**Comment by RichardLitt** [comment]
@acityinohio Is this not something we're interested in doing?

**Comment by acityinohio** [comment]
@RichardLitt still interested! just wanted to close out inactive issues
