### ISSUE TITLE
Focus resources on gathering/analyzing data

### ISSUE THREAD

**Issue by zancas** [ZcashFoundation/ZcashFoundation#25]
How should the Foundation Allocate Resources?

Which projects are most likely to net large benefits?

What things are most in demand by the wider Zcash community?

The first thing the Foundation should focus on is building awareness, mechanisms for ingesting and comprehending the relevant state of the wider market(s).

How _exactly_ to do this is something I don't have a strong opinion on except to say that it seems like several full-time positions could easily be devoted to the task.

My opinion is that hiring several specialists who are willing to accept ZEC in compensation for working on issues like the following would be an excellent First place to devote resources:

*   #13 
*   #9 
*   #8 
*   #4 

Additionally I propose that an Awareness? Analysis? Observation? Working Group, that focuses on data collection and analysis might be a reasonable organization for such an effort.

**Comment by nathan-at-least** [comment]
There's already a working group dedicated to #4 listed here: https://github.com/ZcashFoundation/ZcashFoundation/blob/master/WorkingGroups/ZcashMinersOrganization.md

**Comment by acityinohio** [comment]
Closing this out as part of ZcF GitHub Issues cleanup.
