### ISSUE TITLE
Working Group: zkSNARK / ZKP app devs

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/ZcashFoundation#28]
**What:** A regular meeting of zeroknowledge application developers to discuss tradecraft.

**Why:** We've noticed several blockchain-related projects putting zkSNARK (or other zeroknowledge proving "ZKP" tech) on their roadmaps. This is a newly emerging technical field without well-established techniques. Application developers can learn a lot from each other about design considerations, implementation techniques, available trade-offs, etc…

Specifically, the Zcash Company R&D effort is exploring a much more efficient zkSNARK construction, as well as a reusable/partially-generic parameter setup system that can scale to many users. If current application developers collaborate on this soon enough, all of the systems could benefit from better security and speed.

**Next Steps:**

* If you're interested in joining this group, send your contact info to ``FIXME``.
* If you could help coordinate the group (schedule and facilitate meetings, write monthly updates, see [Working Groups page](https://github.com/ZcashFoundation/ZcashFoundation/tree/master/WorkingGroups#minimum-requirements-for-a-working-group)) let us know!

Once a working group is formed, the coordinator should update this ticket with the relevant links/info.

**Comment by burdges** [comment]
I should've probably posted https://github.com/ZcashFoundation/ZcashFoundation/issues/35 as a comment here.

**Comment by amiller** [comment]
This is now a working group, Josh has agreed to act as the coordinator to keep ti going. https://github.com/ZcashFoundation/ZcashFoundation/blob/master/WorkingGroups/zApps.md
