### ISSUE TITLE
Primeiro Anúncio da Fundação Zcash

### ISSUE THREAD

**Issue by javiermardoness** [ZcashFoundation/ZcashFoundation#29]
Olá Mundo, a Fundação Zcash está pronta e online. Nesse anúncio nós declaramos a missão da Fundação, introduzimos o quadro da Fundação ( feito com seus próprios membros) e explicamos algum dos seus planos iniciais.

Por que nós precisamos de uma Fundação?

O lançamento e crescimento de cada criptomoeda tem sido um pouco diferente. Organizações de suporte, como times Core Developers, Fundações e companhias tiveram todos que suprir diferentes necessidades. É difícil imaginar uma única organização que possa fazer tudo.
Criptomoedas são redes abertas que podem fornecer valiosas infraestrutura para o público geral.Sem uma administração central, a responsabilidade do desenvolvimento e manutenção dessas redes abertas é dividida entre vários stakeholders, incluindo mineradores, desenvolvedores, hodlers e provedores de serviços. No caso da Zcash,  a mais visível, influente, e entidade coesiva é a Zcash Co ( também conhecida pelo longo, nome próprio, Zerocoin Eletric Coin Company), a qual desenvolve o software que recebe a Recompensa do Fundador (FR).

No entanto, para Zcash ter sucesso, ela precisará crescer para representar uma comunidade muito maior e diversa de stakeholders e usuários. Portanto nós visualizamos a necessidade de uma Fundação é primariamente para ajudar essa transição ocorrer.
Mandato da Fundação

Nossa missão, de forma mais ampla, é servir a comunidade Zcash e o público geral como usuários do protocolo e blockchain Zcash.
Sendo mais preciso, nós temos três metas: 1) promover uma saudável e diversa comunidade Zcash, 2) gerenciar o protocolo Zcash e o código fonte com um bem público 3) avançar a ciência da preservação da privacidade das criptomoedas e educar o público a respeito da substância e benefícios desses desenvolvimentos científicos.

Leia mais em ZcashFoundation/MISSION.md

Como nós começamos

Desde cedo no planejamento do desenvolvimento e lançamento da Zcash, Zcash Co planejou separar uma organização independente sem fins lucrativos, para ser financiada em parte com doações de destinatários da Recompensa dos Fundadores. Você pode ler mais sobre isso a partir da perspectiva da Zcash Co em vários desses posts (1) (2).

A partir do 14 de Fevereiro, a Fundação Zcash será implementada no estado de Delaware. Nós estamos atualmente aplicando para o status de sem fins lucrativos 501(c)(3). O quadro inicial de diretores da Fundação Zcash compreende os seguintes membros:

Andrew Miller (tesoureiro)
Peter Van Valkenburgh (secretário)
Matthew Green
Naval Ravikant

Nossa declaração de missão, declaração de valores e esse anúncio inicial, foram formados com contribuição do quadro de membros e vários outros contribuidores (leia mais no arquivo dos CONTRIBUIDORES).

O quadro de membros da Fundação Zcash são voluntários e a Fundação é financiada por doações do público. Vários destinatários da Recompensa do Fundador Zcash (FR), incluindo Least Authority Enterprises, já se comprometeram a doar uma parte para do FR para Fundação.

O que exatamente a Fundação irá fazer?

Isso ajuda a ter um plano concreto, especialmente para criar o hábito de construir prestação de conta pública. As metas da fundação são as seguintes:
Organizar a primeira conferência Zcon. Conferências de criptomoedas, como Scaling Bitcoin e Ethereum DevCons, têm sido muito bem sucedidas em promover conversas entre comunidades e nós planejamentos organizar uma conferência que seja deve padrão, incluindo grande participação de mineradores, desenvolvedores, investidores e mais.
Construir fóruns de discussões e sistemas de votação para reconhecer os vários stakeholders, incluindo ( para começar) mineradores,  token holders, e FR beneficiários. Agora, a Zcash Co é a voz mais clara no cômodo. Fóruns de discussões online já existem para desenvolvedores Zcash e mineradores Zcash, embora seja difícil estimar qual bem eles representam a comunidade como um todo.

Criptomoedas provêm vários mecanismos de construção para votação na comunidade, nomeadamente utilizando "prova-de-trabalho ( ex: votar utilizando hashpower) e usando "prova de participação"(ex: votando através da prova que você possui as chaves associadas com determinada quantidade de moedas). Portanto nós visualizamos o uso de técnicas como essa para implantação de plataforma de discussão complementar, principalmente visando construir e reconhecer o consenso entre diferentes grupos de partes interessadas.

Definindo a estrutura de governança e documentos de política para Fundação. Atualmente, nossas regulamentações são padrões - elas apenas falam que o quadro deve se encontrar anualmente e votar para eleger oficiais e definir políticas. Como o próximo quadro será escolhido? O quadro ( quadro inicial de diretores) é assim chamado por que nossa meta é estabelecer a Fundação com um estrutura efetiva.

Nem todas as fundações foram o sucesso. O que nós vamos fazer diferente?
Uma Fundação não é onisciente e seria um erro tentar morder mais do que podemos mastigar. Fundações de criptomoedas variaram bastante em seus escopos e nem todas foram sucesso completo. Nosso valores de planos estão emergindo mas nós estamos em um acordo sobre vários valores nós acreditamos nos fazem diferente.

Liderando através do exemplo. Criptomoedas são experientes. Nós acreditamos que a Fundação Zcash pode cumprir sua função mostrando um bom exemplo de governância para o ecossistema de criptomoedas para seguir. Nosso planejamos experimentar construindo uma organização robusta que pode criar consenso até mesmo entre vários interesses divergentes.
Inclusividade O ecossistema Zcash consiste de várias subcomunidades, tais como usuários, desenvolvedores, exchanges, traders e pesquiadores em vários países e culturas. A todos eles deve ser dada uma voz com a comunidade Zcash e com as deliberações da Fundação.

Aprendendo de outras entidades no ecossistema das criptomoedas nos apoiamos nos ombros de gigantes. A comunidade de criptomoeda tem ( e tem tido) várias formas de Fundações. Nós estamos inspirados por essas ( tanto no seu sucesso e falhas), e você poderá ver claramente suas influências em nossa organização.

Leia mais em ZcashFoundation/VALUES.md

Por que simplesmente não deixar a Zcash Company fazendo seus próprios negócios?

A resposta é .. nós planejamos! Por agora e nós acreditamos que isso continuará sendo verdade no futuro, os interesses da Zcash Co estão bem alinhados para servir como fiscal do código base. Zcash Co dará certo se a base de usuários crescer, fazendo com que o preço cresça de forma constante também.

Nós pensamos no potencial de pedir Zcash Co para doar algum de seus ativos para Fundação, tais como repositório github da Zcash e marcas registradas. Talvez isso vá acontecer eventualmente, especialmente se a Fundação ganhar confiança como fiscais e líderes. Por outro lado, há um bom argumento para que a Zcash Co tenha incentivo para investir e manter sua propriedade. Doá-la iria reduzir esse incentivo, prejudicando toda comunidade.

Editado, 17 de Março: Adicionado "e companhias" para a lista de organizações apoiando uma criptomoeda. Obrigado Eran Tromer for indicar isso.

**Comment by amiller** [comment]
Closing after adding links https://github.com/ZcashFoundation/zcashfoundation.github.io/pull/11
