### ISSUE TITLE
Anunciando Os Prêmios De Testes de Transação Da Fundação Zcash

### ISSUE THREAD

**Issue by javiermardoness** [ZcashFoundation/ZcashFoundation#30]
A Fundação Zcash tem o prazer de anunciar os três beneficiários do "Prêmio de Teste de Transação" ( também conhecido como "Prêmio de Pioneiros da Fundação Zcash"). Cada "Prêmio de Teste de Transação" vale 33 ZEC. Esses prêmios te a intenção de reconhecer os indivíduos que contribuíram voluntariamente para reforçar a comunidade Zcash, através de manutenção, desenvolvimento e organização.

Os beneficiário são:

MineZcash. MineZcash construiu e manteve a maior da parte da infraestrutura de comunicação da comunidade Zcash, especialmente o https://chat.zcashcommunity.com/ rocket chat. Esse chat vem funcioando desde Novembro 2016 e atualmente suporta mais de 1300 usuários.[tx1][tx2]
Lustro. Lustro opera https://zcha.in/ Esse é o primeiro bloco explorador para Zcash blockchain e também fornece estatística e rede de informação como o número de conexões da rede. [tx1][tx2]
Radix42. Radix42 contribuiu com uma variedade de ferramentas relacionadas a Zcash, e em particular mantêm portas da Zcash4win e Zcash4Mac do cliente de referência Zcash. [tx1][tx2]
Esses são chamados prêmios de "Teste de Transação" porque eles são um considerados um evento único. Esses são significantes porque eles são a primeira instância da Recompensa de Fundadores retornando para a comunidade através da Fundação! No futuro, a Fundação irá organizar seus gastos através de processos mais organizados e inclusivos. Eu estou particularmente animado em relação ao Subsídio de Fundação, que está sendo discutido e com um ticket pendente. https://github.com/ZcashFoundation/ZcashFoundation/issues/2

Ressaltamos que existem vários outros contribuidores da comunidade Zcash que merecem reconhecimento e suporte também, então isso não é de todo abrangente. Se você está interessado em participar da Fundação Zcash e ajudar a determinar seu futuro, os melhores lugares para participar da discussões são o fórum da fundação, #the-zcash-foundation canal no rocket chat ou no nosso github.
Parabéns de novo para MineZcash, Lustro e Radix42!

**Comment by amiller** [comment]
Closing after adding links https://github.com/ZcashFoundation/zcashfoundation.github.io/pull/11
