### ISSUE TITLE
Atualizações da Fundação em Julho de 2017

### ISSUE THREAD

**Issue by javiermardoness** [ZcashFoundation/ZcashFoundation#31]
Olá todo mundo
Esse é apenas um post curto para deixar você atualizado sobre as notícias da Fundação Zcash nos últimos meses. Nós temos feito progressos em configurar a organização e iniciar projetos.

## **Como falar com a gente e se envolver**

Primeiramente, algumas rápidas maneiras de falar
O repositório no Github da Fundação emergiu como o lugar central/autoritativo para todas as atividades da fundação.
Nossa página de publicações no Github tem sido uma área ativa de discussões sobre coisas que a Fundação deveria fazer.
O #the-zcash-foundation channel no chat Rock é um chat ativo.

## **Seja bem vinda Yan Zhu como a quinta membra do quadro da Fundação Zcash**

Yan Zhu é uma desenvolvedora e apoiador ada privacidade online e de tecnologias que aumentam a privacidade. Ela foi umas das desenvolvedoras originais do Secure Drop e atualmente é uma Technologist Fellow at Electronic Frontier Foundation, e também trabalha na Brave como uma desenvolvedora senior de software.

## **Anúncio de emprego: Gerente de projeto de meio-período.**

Nós postamos uma descrição de emprego para gerente de projeto para nos ajudar a executar projetos para a Fundação.

## **Grupos de Trabalho**

Nós criamos uma estrutura de grupo de trabalhos como uma maneira de definir projetos e coordenar voluntários. Você pode propor uma grupo de trabalho hoje. Publicações no Github são uma boa maneira de iniciar discussões sobre idéias de projeto.
Paige da companhia Zcash tem liderado o primeiro grupo de trabalho em “Privacy Preserving Donations for Non-profits”

##  **Atualizações administrativas**

- Nós preenchemos nosso formulário 1023 para aplicar para o status de 501(c)(3) com a IRS.
- Nós postamos todas as nossas reuniões de conselhos e decisões feitas por email.
- Eu tenho feito hangout de “horas de escritório” uma vez por semana ( 12:00 Sexta-Feira ) na maior parte para atualizar e realizar algum trabalho. Me deixe saber ( no rocket chat ) se você está interessado em saber.

**Comment by zookozcash** [comment]
Thank you! :-)

**Comment by jonathascarrijo** [comment]
Javier, obrigado pela contribuição.
Também sou brasileiro, e tenho por função facilitar a cooperação e integração da comunidade Zcash no Brasil e América Latina.
Me avise se tiver alguma forma que possa lhe ajudar, ou se tiver alguma ideia que queira contribuir e que eu possa lhe apoiar.

**Comment by javiermardoness** [comment]
@jonathascarrijo existe alguma exchange brasileira que negocia ZEC? Pensei em entrar em contato com algumas para tentar incluir ZEC no portifólio. Para fazer isso precisaria do seu apoio como representante da Zcash Company. 
Gostaria também de saber mais informações sobre o estágio da ZEC na América Latina.
Obrigado!

**Comment by amiller** [comment]
Closing after adding links https://github.com/ZcashFoundation/zcashfoundation.github.io/pull/11
