### ISSUE TITLE
A Fundação Zcash dá as boas vindas para o Gerente de Programas Senior

### ISSUE THREAD

**Issue by javiermardoness** [ZcashFoundation/ZcashFoundation#32]
Estamos felizes em anunciar que Josh Cincinnati foi contratado como Gerente de Programas Sênior para Fundação Zcash. Josh é um membro ativo da comunidade da criptomoeda, foi um Developer Advocate na BlockCypher, uma companhia especializada em APIS para Bitcoin, Litecoin, Ethereum e outras criptomoedas. Ele agora é um Developer Advocate no Lyft, um cargo que está exercendo concomitantemente enquanto trabalha para Fundação Zcash meio horário.

Uma lista mais detalhada dos deveres do Gerente de Programas Sênior pode ser achado na publicação do Github que fizemos. Resumindo, o Programa Sênior de Gerenciamento vai acelerar o trabalho da Fundação para construir uma plataforma para comunidade Zcash - coordenando comunicação através dos membros da comunidade, organizando eventos e grupos de trabalho, criando e promovendo marketing e mais. Josh alinha fortemente com a Missão e Valores da Fundação Zcash.

Ele é agradecido por aprender com outras contribuições de criptomoedas e aplicá-las para a Fundação crescer.

A Fundação enfrenta oportunidades únicas e desafios - os quais Josh está animado para enfrentar como a primeira contratação da Fundação Zcash. Nós estamos ansiosos para colaborar com ele.

**Comment by amiller** [comment]
Thanks @javiermardoness, these are invaluable and we'll be able to link to these and close these issues just as soon as the #33 website upgrade goes through. In the mean time, please accept the :+1: as an indication that these translations are received and acknowledge :)

**Comment by javiermardoness** [comment]
Thats great!

**Comment by amiller** [comment]
Closing after adding links https://github.com/ZcashFoundation/zcashfoundation.github.io/pull/11
