### ISSUE TITLE
Zcash Site Overhaul (i18n, SSL, better design/workflow)

### ISSUE THREAD

**Issue by acityinohio** [ZcashFoundation/ZcashFoundation#33]
This is a parent issue to a few disparate things that are somewhat related. I think an overhaul would enable solving these issues in a complete way rather than trying to work with the current limitations of GitHub pages/Jekyll. Child issues (possibly missing some, feel free to add if anyone thinks its appropriate):

#18, #19, #20, #22, #24, #29, #30, #31, #32

**Comment by mineZcash** [comment]
I agree, the GitHub pages format was a good short term solution to quickly get a site up for no cost but in the long run a more adaptable platform is needed. 
I personally use WordPress since it is well supported, secure, adaptable, lots of professional themes and has a much more user friendly backend. I can provide a quick mock-up for evaluation if needed.

Cloudflare is also a good addition to the site to prevent DDoS attacks and make use of thier universal SSL certificate.

Or is there another platform that you have used before that you would prefer?

**Comment by acityinohio** [comment]
Thanks @mineZcash! Glad you agree. I was thinking of using a suite of AWS services: S3 + CloudFront + Route 53. SSL cert is free and CloudFront is relatively cheap as CDNs go.

As far as static site generation, my initial thought was to see if there was a way to do a combined workflow from GitHub; keep the md files of the current site but have a running cronjob of sorts to pull new changes and distribute to S3. That may be...overengineered to start, but could be nice. Was thinking of using Hugo for static site generation, but also open to continue using Jekyll sans GitHub pages. Will probably spend sometime evaluating a few options this week.

Longer term (waaay outside the scope of this issue) I'd love to do something fancy and decentralized as our primary Zcash Foundation gateway but I think we'll have to wait for some of those solutions to mature. Good to have a goal though. :)

**Comment by zmanian** [comment]
I've been using Firebase free static site hosting for https://zaki.manian.org and several other sites.

TLS certs are free for Firebase sites. TLS is terminated by the Google edge which I have a lot of confidence in and you benefit from Google CDN/SDN.

Basically I put to github and then a travis CI job posts to firebase.

Been really happy with it. I specifically wanted to avoid Cloudflare

**Comment by acityinohio** [comment]
I didn't even have to say "blockchain" 3 times and you're here @zmanian. ;)

Thanks for the input! Looks like yours is also a Hugo site, are you pretty happy with that tool as a site generator?

**Comment by zmanian** [comment]
I have been happy with hugo so far.  it's brew installable on a Mac and go get / download a binary everywhere else.

There are like 3 commands to do a post.

There was some kind of rant about hugo and rss feeds on HN yesterday that I didn't read.

**Comment by mineZcash** [comment]
I was looking into the Github integration and found this really cool plugin thats basically a webhook. It will allow WordPress to become similar to Jeckyll for showing revisions/issue/pull requests but still have the WordPress ecosystem for making the frontend and other fancy plugins.

https://wordpress.org/plugins/wp-github-sync/

https://github.com/mAAdhaTTah/wordpress-github-sync

**Comment by acityinohio** [comment]
Closing this out as a rebrand/web redevelopment is in process (a la #54).
