### ISSUE TITLE
Use as a Medium of Exchange - Grant Idea

### ISSUE THREAD

**Issue by Hohhle** [ZcashFoundation/ZcashFoundation#34]
I propose that the ZCash foundation should illustrate the viability of ZCash and crypto-currencies as a medium of exchange using a short to medium length basic income type model experiment. 

In order to ensure a greater likelihood of success, this project would initially require that a project representative and several persuasive board members meet with government leaders of smaller sized countries which would be ideal.

I would recommend selecting one or several of the nations from the Caribbean and South American CARICOM organization that are sovereign, as well as smaller in population and land area (comparatively speaking). This would encourage a greater saturation for commerce and participation in the project to amplify the experiment.

The goal, in addition to ensuring its legality, of participation of the governments would be to assist in providing ease of use and "blessing" the use of cryptocurrencies in commerce with minimal barriers. The government could also provide an point of exchange for utilities such as electricity, water, and garbage disposal.

Of the CARICOM members, the countries which would provide the biggest "bang-for-buck" would be those with the lowest Purchasing Power Parity to the USD, as the most common fiat benchmark is the USD. Those with a population less than 1 million, from smallest PPP to largest, would be: 

Guyana, Belize, Saint Vincent and the Grenadines, Suriname, Saint Lucia, Grenada, Dominica, Saint Kitts and Nevis, Antigua and Barbuda, Barbados, and The Bahamas.

Other considerations for targeted countries would be recommended, such as: mobile/smartphone penetration, ease of identity verification, population density, language barriers, etc.

After selecting a specific locale, country, or region for the project, a criterion would be developed for the distribution of the funds; in addition to the optimal distribution method, length, and amount.

I would recommend either targeting a specific demographic with a greater propensity to spend the funds instead of saving, and/or requiring a specific percentage/amount of the funds dispersed to the ZCash recipients be spent at "registered" or known transparent addresses (such as grocery, utilities, government taxes, etc.)

Another crucial aspect to encourage ease of use is the penetration of mobile phones and internet in the several countries. In order to facilitate the use of crypto-currencies like ZCash, the targeted countries need to have a high usage of mobile phones (specifically smartphones) and the ability/ease of internet access. The most likely wallet of choice for the recipients is mobile devices hot wallets (such as: Jaxx, Coinomi, or other legitimate "you-know-the-private-key-seed.") Several of these countries have made significant improvements in their rankings, specifically mobile-cellular subscriptions:

"
St. Kitts and Nevis experienced a very significant and rapid increase in active mobile-broadband
subscriptions, building on a strong performance in mobile-cellular subscriptions. The mobilebroadband
penetration rate increased from just 18.6 per 100 inhabitants in 2014 to 71.0 in 2015.
A similar trend can be observed in Grenada, where mobile-broadband penetration rose from
only 2.6 per 100 inhabitants in 2014 to 28.8 in 2015. Dominica saw an increase in active mobilebroadband subscriptions from 29.3 to 42.2 per 100 inhabitants in the course of the past year,
as well as substantial improvements in fixed-broadband penetration, the proportion of Internet
users, and households with access to the Internet.
"
http://www.itu.int/en/ITU-D/Statistics/Documents/publications/misr2016/MISR2016-w4.pdf
(Labelled Page 22)

Identity verification is needed to prevent abuse and fraud of against the program for the intended recipients of the experiment. The use of electronic identity verification would enable ease and automation. A preliminary search shows several of these countries received grants for implementation of an electronic IDs in 2014. 
http://www.nowgrenada.com/2014/02/multi-purpose-id-mpid-system-launched/

I believe that even a modest grant targeting a specific locale/country, with proper parameters, would work well for this experiment and illustrate the viability of crypto-currency in commerce as a medium of exchange - ending the long-standing coffee debate once and for all!

**Comment by acityinohio** [comment]
@Hohhle thanks for thoughtful suggestion! Unfortunately I doubt the Foundation would be able to fund a full UBI-style program within the parameters of the [Grant Program](https://github.com/ZcashFoundation/GrantProposals-2017Q4)–since the Foundation only has ~$80,000 to award across all projects, it'd be difficult to do something like this justice (e.g., doing the math on the [UBI trial in Finland](https://www.theguardian.com/society/2017/feb/19/basic-income-finland-low-wages-fewer-jobs) suggests a cost of roughly €13.4mm for a year-long experiment).

I'm going to close this out, but if you can think of a smaller-scale version of this you'd like to submit, please do—and if you don't mind, please submit it as an issue here instead: https://github.com/ZcashFoundation/GrantProposals-2017Q4/issues
