### ISSUE TITLE
Zero-knowledge proof standards

### ISSUE THREAD

**Issue by burdges** [ZcashFoundation/ZcashFoundation#35]
In the longer term, ZCash should encourage efforts to "standardize" zero-knowledge proof schemes, after first encouraging the further development of zero-knowledge proof schemes to the point where standardizing any makes sense. 

I suspect the primary benefit of, and perhaps mechanism for, standardizing zero-knowledge proof schemes would be to achieve larger collaborative trusted setups for different future protocols. 

In ZCash, anonymity does not depend upon the trusted setup per se, provided you do not reveal the public keys involved, but a more trusted setup still benefits ZCash.  There are also supposed anonymity protocols involving zero-knowledge proofs where anonymity does depend upon the trusted setup phase, including all "divisible ecash" protocols. 

If enough protocols were eventually using the same zero-knowledge proof scheme, then one could imagine people interested in different protocols contributing to one another's trusted trusted setup phases, or even producing trusted setup parameters as a byproduct of the proof-of-work function for ZCash.

**Comment by mineZcash** [comment]
As you mentioned, the current trusted setup does not risk the privacy of Zcash users but if the shards of the public key are not properly destroyed then it could allow false verification of notes, which would allow an attacker to forge coins. 
The next step they are taking is a larger multi-party trusted setup utilizing a accumulator that will allow it to scale to a much larger number of participants, thereby mitigating risk https://github.com/zcash/zcash/issues/2247

I think the best long term solution is to phase out the trusted setup completely and support research in the new area of STARKs which are true zero-knowlege proofs and do not require a trusted setup. Right now this STARK research is being headed up by Professor Eli Ben Sasson (speaks about them here: https://youtu.be/kYmnXxs9kUM)
Even though the proof size right now is to large to be viable for a production block chain like Zcash, it looks like STARKs will become the future standard for zero-knowlege proving systems.

**Comment by acityinohio** [comment]
Closing this out as part of the new working group—thanks for the suggestion/comments @burdges @mineZcash !
