### ISSUE TITLE
Anunciando o Programa de Recompensas da Fundação Zcash

### ISSUE THREAD

**Issue by javiermardoness** [ZcashFoundation/ZcashFoundation#36]
Estamos orgulhosos de anunciar o primeiro Programa de Recompensa da Fundação Zcash - uma extensão natural dos [três pilares da Missão da Fundação](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/MISSION.md) para servir a comunidade, protocolo e ciência da criptografia em geral. Nós estamos procurando por novas idéias que valem a recompensa em ZEC, melhor descritas pela [Chamada por Propostas](https://github.com/ZcashFoundation/GrantProposals-2017Q4):

“O escopo de atividades é amplo e pode incluir: desenvolvimento de software ( exemplo: software de carteiras) infraestrutura de desenvolvimento e manutenção ( ex: hospedagem de fóruns) educação e divulgação, ciência, pesquisa e muito mais.

A Fundação Zcash é uma organização sem fins lucrativos e portanto está interessada em financiar propostas que visam servir o público e não a monetização. Não buscamos financiar startups que podem buscar crowdfunding ou venture capital, nem websites que vendem anúncios. A escala pretendida é 1 a 6 pessoas/mês de esforço mais despesas diretas como servidores e serviços de nuvem.”

Nosso tema para essa rodada de recompensas reside firmemente no primeiro pilar da[ Missão da Fundação](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/MISSION.md): desenvolvimento comunitário, especificamente "infra-estrutura comunitária". Há várias oportunidades para construir serviços e infraestrutura para apoiar o ecossistema Zcash e nós sinceramente esperamos que você considere aplicar. Quer ajudar para pensar algumas idéias? Veja nosso [open Grant project wiki](https://github.com/ZcashFoundation/ZcashFoundation/wiki/Grant-Project-Ideas). Idéias devem ser enviadas para a devida página de [publicações no Github até 15/09/2017](https://github.com/ZcashFoundation/GrantProposals-2017Q4/issues) - não podemos esperar para vê-las.

Você pode ler mais sobre o processo de Recompensa em [Chamada por Propostas](https://github.com/ZcashFoundation/GrantProposals-2017Q4). A Fundação é especialmente grata pelo Comitê de Revisão de Recompensas—Alex Biryukov, Eran Tromer, Gibson Ashpool, Vlad Zamfir, and Zaki Manian— por se voluntariarem para revisar as propostas. Além do programa de Recompensas, a Fundação vai aumentar suas atividades e divulgá-las nos próximos meses e estamos animados para engajar a comunidade! Fique ligado.

**Comment by amiller** [comment]
Closing after adding links https://github.com/ZcashFoundation/zcashfoundation.github.io/pull/11
