### ISSUE TITLE
Set up email infrastructure for z.cash.foundation

### ISSUE THREAD

**Issue by acityinohio** [ZcashFoundation/ZcashFoundation#38]
Need listservs and individual addresses.

**Comment by nathan-at-least** [comment]
Note, for newletters on working group status in particular, I have a request to ensure each newsletter issue lives at a publicly available stable URL. If those newsletters are published as mailing list posts, let's follow up on the listserv setup with setting up a URL-stable public archive interface.

It might be wise to break this into a separate followup task if it takes enough time/effort/complexity.

Note, I said a simliar thing over at https://github.com/ZcashFoundation/ZcashFoundation/issues/6#issuecomment-324966094

**Comment by einotna** [comment]
Re: g-suite setup. @amiller , were you able to add MX records to our domain? Please see attached images.
![image 2](https://user-images.githubusercontent.com/32369344/31027939-fbd03542-a500-11e7-950c-102478f1fdcf.png)
![image 1](https://user-images.githubusercontent.com/32369344/31027941-fbe8578a-a500-11e7-95ab-43694f276223.png)
![image](https://user-images.githubusercontent.com/32369344/31027940-fbe5b9da-a500-11e7-82ec-16aa35b3529c.png)

**Comment by amiller** [comment]
ok should be done now

**Comment by acityinohio** [comment]
Definitely done for now, should have closed this a while ago.
