### ISSUE TITLE
The Zcash Foundation Gives The Appearance of Being Understaffed

### ISSUE THREAD

**Issue by zancas** [ZcashFoundation/ZcashFoundation#39]
As far as the marginally informed public is concerned (I'm serving as a representative) there's only one part time employee of the Zcash Foundation, @acityinohio .  This is a good thing!  One is non-zero, yay!   I would like to know what the plan is for hiring the next employee.

Is there a process whereby the most urgent needs are being identified and appropriate roles being defined?

Once a role has been defined how will we learn about the opening?
Will there be a new issue announcing the position?
Is there an approximate timeline for what we can expect?
Is my assumption that there will be hiring in the immediate future even correct?
Who has the time to answer all of my questions?
Should The Foundation hire someone to answer my questions?

**Comment by amiller** [comment]
All good questions, thanks for the much needed feedback Za!

We do not yet have a process defined for identifying urgent needs or identifying roles to fill. Points well taken though. So far it's driven by board members' initiative, and input from the public / folks who show up. We've been discussing an additional "Operations" role, an "Executive Director" role, and hiring someone just for organizing the Zcon0 conference.
- I definitely think new positions should be announced with an issue. 
- Timeline is undefined yet, I would estimate "short term" i.e. within 2 months.
- I think the Program Manager role includes responding to or at least routing questions like this (if I don't show up first) :) 

In my opinion the biggest obstacle to forming a process to hire people, is building a cycle of feedback / representation from this community more broadly (I personally feel a sense of obligation to not spend too rapidly until that is established). The obstacle to that in turn is in part the lack of visibility. The Program Manager has committed to several tickets involving outreach (including addressing your earlier questions about visibility) to get more folks involved.

Maybe we should have multiple independent program managers that are empowered to make funding allocation decisions as a way of moving faster.

Leaving this issue open until there's a more concrete answer...

**Comment by zancas** [comment]
I think hiring more people with the ability to allocate resources seems like a good idea.

I also think that a role that includes translating relevant sites (like this one) into Mandarin, is an urgent need.

Perhaps The Foundation could prioritise hiring a native Mandarin speaker?

Perhaps that individual could be the first person to work pseudonymously for The Foundation.

**Comment by radix42** [comment]
Over one quarter of my downloads of zcash4win are from China, so I'll
second getting as much translated into Mandarin as a urgent need

**Comment by acityinohio** [comment]
Thanks for the continued feedback @zancas (and @radix42)! We are in the process of hiring additional contractors for basic administration—per what @amiller mentioned, the Foundation has some urgent admin needs (like accounting/operations) that we are aggressively pursuing, and hope to have news there to report soon.

On translations in particular, we have Translation working group that has been contributing on a volunteer basis: https://github.com/ZcashFoundation/ZcashFoundation/blob/master/WorkingGroups/ZcashTranslation.md
As one of the other working group coordinators/program manager, I'm also putting some effort into general working group process/organization, but it's possible that we could coordinate the Mandarin translations as volunteer activity within the context of the working group linked above.

**Comment by amiller** [comment]
We've now hired an additional staff member, Antonie Hodge (@einotna)! Antonie will be our Director of Operations and taking the lead on our logistical and administration needs. Blog post pending :D

**Comment by acityinohio** [comment]
Blog post here: https://z.cash.foundation//blog/welcome-antonie/

In concert with hiring @einotna , we've also contracted with an accounting firm to help reconcile our books. I'm going to close this out, but if there are additional roles that others think we should be hiring, feel free to open individual issues per @amiller's suggestion, and thanks as always for the feedback!
