### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#40]
We have a few backlogged documents to push to the repo eventually, mainly our 1023 application for non-profit status still to push on the website. We should write down some process for making sure we're not forgetting anything!

**Comment by acityinohio** [comment]
I think we've done a good job of getting this in order on our side, but we definitely need to add to our website (something to do early next year).

**Comment by acityinohio** [comment]
Added IRS determination letter, Bylaws, and Certified Articles here: https://github.com/ZcashFoundation/ZcashFoundation/commit/058b46b20ae1a425f029b95115b31c1d773b2670

Would like to have this on our website instead of GitHub but will make that part of a broader web redesign.
