### ISSUE TITLE
Learn from Monero and Dash on effective community-made funding decisions

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#41]
The Monero community has done a great job in developing open and crowd-driven funding. 

The getmonero website features an excellent crowd-funding tool, where users can post funding requests and they can be filled by donors.
https://forum.getmonero.org/8/funding-required

This solves two problems: One is it helps with collective decision making, since the community watches the project proposals and appealing projects get funded. Second, it serves as a donation collections.

Grant matching could be a good way for the Zcash Foundation to get some of the benefit. Users would still need to donate money towards proposals registered this way, but the Foundation could amplify the amount.

**Comment by acityinohio** [comment]
I think something akin to the forum-funding model will be part of the evolution of the Grants program (e.g. community funding shows interest and then we match if the other party is willing to be KYC'd), and we'll definitely draw from Monero and Dash's experience here. Closing for now.
