### ISSUE TITLE
Courage dá as boas-vindas para Doações Zcash

### ISSUE THREAD

**Issue by javiermardoness** [ZcashFoundation/ZcashFoundation#42]
Courage, a organização internacional que apoia locutores da verdade, vai começar a aceitar doações em Zcash (ZEC) a partir de hoje. Apoiadores podem fazer doações para a organização ou para os nosso beneficiários individuais na seguinte URL:
https://couragefound.org/donate

Zcash é um fork do protocolo bitcoin que permite que pagamentos sejam feitos com maior privacidade com o uso de criptografia avançada chamada prova de conhecimento-zero. Desde o lançamento da Zcash em Outubro de 2016, seu ecossistema tem expandido rapidamente a medida que a ineficiência de privacidade do Bitcoin é melhor entendida. Courage tem trabalhado com a Fundação Zcash para introduzir soluções de pagamentos e está encorajando outras organizações a fazer o mesmo. 
Sarah Harrinson da Courage disse:

“Sistemas de pagamento são politicamente neutros. Courage sempre apoiou o uso de criptomoedas - nós aceitamos Bitcoin desde o primeiro dia - para evitar censura e melhor proteção da fonte. Vários dos locutores da verdade que nós apoiamos tiveram acesso limitado aos seus fundos: doadores para fundo de defesa de Barret Brown viraram alvos e vigiados, e teve uma tentativa de confiscar essas doações, isso mencionar o terrível bloqueio bancário experenciado pelo WikiLeaks. Estamos muito animados para trabalhar com a Fundação Zcash para avançar nossas metas em comum em relação  privacidade e segurança online. Análises de linkabilidade do bitcoin mostram que padrões mais avançados de privacidade são necessárias e Zcash resolve esse problema. Somos extremamentes gratos à comunidade Zcash pelo seu suporte.”
Andrew Miller, Presidente da Fundação Zcash disse:

“Ajudar outros organizações sem fins lucrativos se beneficiarem das criptomoedas é uma parte chave da missão da Fundação Zcash. Entrar em contato com Fundação Courage como primeiro estudo de caso foi uma escolha natural, uma vez que eles possuem requerimentos claros para doações privadas e resistência de censura, e eles também possuem experiência em expertise para aceitar seguramente doações de Bitcoin. Nós estamos especialmente animados para trabalhar com a Fundação Courage para compartilhar e documentar a experiência deles utilizando Zcash, uma vez que a experiência deles pode servir como um modelo para ajudar outras organizações sem fins lucrativos oferecerem aos seus doadores uma ferramenta de preservação de privacidade para contribuições financeiras.”

Nota dos editores
Zcash é um fork do protocolo bitcoin, a primeira e mais utilizada criptomoeda blockchain. Isso significa que ela mantêm sua própria blockchain e moeda de token. Zcash cria no trabalho já existente do time de desenvolvimento central do Bitcoin para permitir transações de dados que já estão criptografados mas ainda verificáveis pelos nós da rede, utilizando prova de conhecimento zero. Adicionalmente às transações criptografadas pelo endereços protegidos, Zcash possui, por enquanto, um endereço público como o do bitcoin, conhecido como endereço transparente. Courage vai apoiar os dois tipos de endereço para oferecer aos doadores mais opções.

A Fundação Zcash é registrada como uma organização sem fins lucrativos servindo a comunidade Zcash e promovendo privacidade financeira.
https://z.cash.foundation/

Courage é uma organização internacional que apoia aqueles que colocam-se em riscos para realizarem contribuições importantes para o registro histórico. Os primeiros beneficiários pela organização foram Edward Snowden e agora suporta vários outros, incluindo Jeremy Hammond, Barret Brow, Chelsea Manning e Lauri Love.
https://couragefound.org

**Comment by acityinohio** [comment]
Thanks @javiermardoness ! Closing with link back for now, per the other translations: https://github.com/ZcashFoundation/zcashfoundation.github.io/commit/df9378a8fd2391de471684fe834c897e53a67c92
