### ISSUE TITLE
Monthly "newsletter".

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/ZcashFoundation#43]
A monthly newsletter summarizing the status and plans for working groups and the overall Foundation would help get the word out on ongoing initiatives. If each post has a stable URL that's really helpful for historical links, too, such as "back in February, the Foundation did X, see &lt;link&gt;".

As inspiration, I fondly recall the "Tahoe-LAFS weekly news" which posted RST format to a mailing list and then also rendered it at URLs [such as this](https://tahoe-lafs.org/~marlowe/TWN71.html).

**Comment by amiller** [comment]
+1, I think this can be folded into a working groups update

**Comment by nathan-at-least** [comment]
Any progress on this front?

**Comment by acityinohio** [comment]
@nathan-at-least I'm sorry for the extreme delay here, but now that we've got a general list I've got this rolling, first post out here:

https://lists.z.cash.foundation/pipermail/general/2018/000006.html
https://forum.z.cash/t/end-of-february-2018-update/27457

I'm planning on keeping the monthly cadence up and cross-posting to the forums. Thanks again for suggesting it!

**Comment by nathan-at-least** [comment]
I meet your delay and raise by several more months. ;-)

This is perfect! Thanks.

**Comment by acityinohio** [comment]
no worries @nathan-at-least! I actually missed my cadence goal on this because of my cross-country move—but am planning another mailing this week for april. :smile:
