### ISSUE TITLE
Curated Research Topics

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/ZcashFoundation#5]
While doing feature planning for the Zcash protocol development with the Zcash Company, we have a firehose of useful research ideas. Meanwhile, we hardly have time to look into even the most promising. 

I would love to publish a list of topics and/or problem descriptions. It would be great if anyone could post these, and in that case it would help to have some kind of refinement process so that proposals that were vague, not obviously related to the broad area, or have other issues could be refined before making it onto a mature list of topics.

This may or may not tie into a grant program. I see value in keeping them somewhat decoupled: maybe grants should be awarded for things unrelated to these research topics, and maybe research topics would be expounded upon more widely if there are no constraints related to the grant program. That being said, obviously there would be a good intersection of grants for researching well specified problems.

**Comment by acityinohio** [comment]
Closing this as part of ZcF GitHub Issues cleanup.
