### ISSUE TITLE
Moderation policy for WG mailing lists?

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#51]
The Zcash Foundation hosts mailing lists for working groups. #38 #11 https://lists.z.cash.foundation/mailman/listinfo/
However, we haven't fleshed out our moderation policy, if any, yet.
We intend to leave the mailing lists mostly up to the individual working groups, so we should hope that for the most part working groups moderate themselves.

The Zapps working group seems to be the first to take off with engaging public discussions, especially surrounding the Powers of Tau snark setup ceremony. 
https://lists.z.cash.foundation/pipermail/zapps-wg

Moderation is easy when everyone's roughly incentive-aligned and cooperating. Working groups can hopefully develop moderation policies on their own as the need arises. Since the Foundation is hosting the mailing list service though, we can't entirely abdicate responsibility. So, we should be proactive in writing down what our top-level policies would be.

This issue could be closed with a resolution about the Foundation's moderation policy. Or it can linger open as a discussion about what this policy could be.

Notes:
- we have a VALUES document already which may be helpful: https://github.com/ZcashFoundation/ZcashFoundation/blob/master/VALUES.md
- the Zcash company has a code of conduct for developers we could borrow from: 
https://github.com/zcash/zcash/blob/master/code_of_conduct.md

**Comment by acityinohio** [comment]
Closing this out; during Zcon0 we relied on the Values doc as our guiding list of principles when it came to communication and respecting fellow conference goers (could apply here as well).
