### ISSUE TITLE
Hire PR firm

### ISSUE THREAD

**Issue by acityinohio** [ZcashFoundation/ZcashFoundation#53]
To help with #12/explaining the difference between the Foundation and the company. Ideally a part-time contract, might extend into a full-time Comms/Marketing role.

Right now I'm reaching out to Washman and Strangebrew, but if there are other suggestions would love to hear them.

**Comment by prahaladbelavadi** [comment]
I'd like to give this a shot. @acityinohio 
I'm yet to deep delve research into Zcash and I should soon be able to put together an article differentiating [foundation](https://z.cash.foundation/) and [company](https://z.cash/).

It'd need to be reviewed for errors and corrections tho
What say

**Comment by acityinohio** [comment]
Closing this out as part of ZcF GitHub Issues Cleanup.
