### ISSUE TITLE
Hire Web Designer and/or Developer

### ISSUE THREAD

**Issue by acityinohio** [ZcashFoundation/ZcashFoundation#54]
To help with an overall redesign of the website (#33).

**Comment by amiller** [comment]
It would be cool if we could mirror content between our various platforms. Like a summary of forum conversations should be sent every so often to our mailing list. Posts on the mailing list could be automatically tweeted about. Also, it would be useful to set up measurements for each of the platforms so we can see how effective they are.

**Comment by acityinohio** [comment]
@sonyamann is working with @RichardLitt on this, so considering it closed (and new website coming!)
