### ISSUE TITLE
Community proposal matched-funding program.

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/ZcashFoundation#55]
I'd like to see the addition of a grassroots community selection process for funding. It looks something like this:

- anyone may propose any project within certain acceptable guidelines, along with a target budget.
- anyone may fund any such acceptable project by making a donation.
- the Zcash Foundation has a fund for matching such community-driven donations in some way (ex: 1:1 matched funding).

I personally would like to see the guidelines for acceptable projects be as broad as possible to match the Foundation's mission and values (for example, not requiring any specific relationship to Zcash, apart from the funding mechanism).

There may be some issue in verification, for example, if someone proposes to raise 0.1 ZEC for pizza and soda at a "Blockchain education event", then successfully receives funding from the community and the Zcash Foundation, and then no such event occurs, it would be nice to be able to prevent that or at least notice that it happened.

A distinct but complementary function would be a bounty system, where community members could pledge ZEC on the condition that someone can complete a particular kind of project.

Note: I see this as entirely separate from the Grant Program and I'd personally like to see both operated by the Foundation.

**Comment by tromer** [comment]
Interesting idea! Some practical notes:

- Such donation-matching would still require most of the review process done in the Grants, to ensure that the projects are within scope, realistic, etc.
- There's the issue of people trying to cheat the system by donating to themselves and asking the Foundation to match that. The Foundation does not have good tools to detect this, especially when participants and donors are pseudonymous, and when there are many small donations.
- The Foundation's disbursement procedure involves nontrivial legal/tax procedures with the recipient.

So practically, the Foundation's administrative and review bandwidth would still be a bottleneck.

What kind of scope or dynamics are you aiming for, that cannot be achieved within the framework of the Grants?

**Comment by nathan-at-least** [comment]
I had in mind a few qualities that I see as distinct from the Grant Program.

1. I wanted to allow for smaller, simpler, more inclusive proposals, such as "I'm hosting our universities first zkSNARK student group next Tuesday and would like $50 to print 250 copies of this poster design <link> that I made." My thinking is that the scope here in budget and time is too small to fit into the Grant Program structure.

*Alternative Proposal:* The Grant Program could add different "tracks" for different scopes of projects to allow for both smaller projects with a lower barrier to entry (ex: community events) and larger projects with more scrutiny and potentially larger budgets (ex: R&D projects).

2. I wanted "grass-roots" scale. This is why I wanted to minimize oversite of the Foundation (although that has serious hurdles that @tromer pointed out above). For example, if a community group could form in a country unfamiliar to all current Foundation participants and get bootstrap funding from the Zcash project somehow, that seems powerful. Again, as @tromer points out, if there's no oversight we have no idea if such a community would be relevant or maybe even just fraudulent.

*Alternative Proposal:* Maybe a different approach to this with better oversight would be some kind of federation or franchising of "Zcash community groups" for different regions.

3. I wanted "grass-roots" decision making, both for a sense of buy-in, and to potentially find value the GP review committee wouldn't see. Imagine a proposal like Cryptokitties before the world knew about Cryptokitties. Would the Grant proposal reviewers consider it relevant enough, even though some public population would love it?

*Alternative Proposal:* We might be able to achieve this by streamlining the Grant review process to allow more public participation. The first phase of grants was open to public comment via Github, and I'm not exactly sure how to streamline this better, but can vaguely imagine a website tailored specifically for proposals and reviews that has a low barrier entry for "typical Zcash enthusiasts" (who may not be technical and may find github tricky).

**Note:** this ticket was inspired by reading Andreas Brekken's Dash review, specifically the section on [using a Dash masternode to vote and propose funded projects](https://shitcoin.com/dash-a-governance-and-privacy-coin-thats-surprisingly-easy-to-use-11160e565ce0#0ba3). (Keep in mind that the system presented there may be gameable, not actually decentralized, etc… I am not certain. It's the vision that I like.)

**Comment by tromer** [comment]
@nathan-at-least, on your point 3:
>  Imagine a proposal like Cryptokitties before the world knew about Cryptokitties. Would the Grant proposal reviewers consider it relevant enough, even though some public population would love it?

Speaking as a review committee member: definitely yes, especially if there were comments on the Github ticket expressing well-reasoned support. The committee did accept several proposals that were not personally exciting to any of the members at first glance, after factoring in community input. An explicit goal of the process was to have the committee serve as both experts and curators, and I think it worked well.


> imagine a website tailored specifically for proposals and reviews that has a low barrier entry for "typical Zcash enthusiasts" (who may not be technical and may find github tricky). 

I've heard the claim that Github is difficult for non-techies before, but never understood it. Sure, setting SSH keys etc. is messy, but not needed here. To post a comment, all you need is to create an account, open the Issue, scroll to the bottom, enter text in the edit box and click "Comment". Is this different than any other plausible platform?

**Comment by acityinohio** [comment]
Very much love the idea of integrating something like this into the next evolution of the Grants—as I mentioned in #41. Closing this out for now.
