### ISSUE TITLE
update the Foundation's Mission

### ISSUE THREAD

**Issue by zookozcash** [ZcashFoundation/ZcashFoundation#60]
The Foundation's Mission is currently “serving the Zcash community and promoting financial privacy”.

On the other hand, https://z.cash.foundation/blog/zcash-foundation-officially-nonprofit/ described it as “building internet payments and privacy infrastructure for the public good”.

What did the Foundation describe its mission as in its application for 501(c)3 status to IRS?

I'd support editing it to reflect the intent of the Foundation to promote the public good, potentially including such things as helping people who aren't (yet?) Zcash coin-holders, helping people who are the holders of other sorts of coins, and contributing to the public good in more ways, such as financial inclusion, and potentially other applications of blockchain technology (voting, identification, logistics? smart contracts/autonomous orgs?)

**Comment by acityinohio** [comment]
I agree @zookozcash—this should be edited to reflect the application. To be transparent we've actually uploaded the 1023 application online here, which you can read here: https://github.com/ZcashFoundation/ZcashFoundation/blob/master/IncorporationDocs/Zcash%20Foundation%201023.pdf

The substantive portion of the application was drafted by @valkenburgh and I believe incorporated feedback from the Board, although the minutes aren't quite explicit (but also publicly available): https://github.com/ZcashFoundation/ZcashFoundation/blob/master/board-documents/minutes/2017-04-05.md

I'd be happy to take a stab at updating the Mission doc to reflect this.
