### ISSUE TITLE
Develop a Brand Book for Zcash

### ISSUE THREAD

**Issue by tloriato** [ZcashFoundation/ZcashFoundation#61]
I'd like to raise a discussion about the need to create a strong Brand Book | Brand Identity | Visual Identity around Zcash. We currently only have logos, [source](https://z.cash/press.html).

I feel like this would be essential for the current efforts regarding the research and development of better UI/UX as I have been following. 

Honestly I'm not sure if this would be a Zcash Company or a Zcash Foundation job, and I'd like to apologize because of that.

----------------------

Brand Books I've seen (and loved) in Crypto:
- [Ethereum](https://ethereum.org/images/logos/Ethereum_Visual_Identity_1.0.0.pdf)
- [Decred](https://decred.org/media/visual_toolkit.pdf)
- [FirstBlood](https://s3.amazonaws.com/firstblood-images/brand-doc/brand_doc.pdf)

**Comment by tloriato** [comment]
Related: #33 #54 #53

**Comment by tromer** [comment]
Related: https://github.com/zcash/logos/issues/4 https://github.com/zcash/logos/issues/3

**Comment by tloriato** [comment]
More:

[Zcoin Branding](https://zcoin.io/branding/)

**Comment by acityinohio** [comment]
Closing this out for ZcF GitHub issues cleanup—currently I think it's more the Company's purview, but as things evolve it will become a shared responsibility to build this together.
