### ISSUE TITLE
SSL error on listserv

### ISSUE THREAD

**Issue by zookozcash** [ZcashFoundation/ZcashFoundation#62]
I heard that one of the grant recipients had posted an update on their progress to a mailing list, so I clicked on a link to "listserv", but I see this:

**Comment by zookozcash** [comment]
![31891817-e4bf-4456-b217-ee2ab1b31fe2](https://user-images.githubusercontent.com/16416064/36625481-82668be2-18dd-11e8-9c24-39b5e438e773.png)

**Comment by acityinohio** [comment]
The SSL issue was brought up before and the mailman provider fixed some variant of it—did a little bit of testing with devices I had available and the redirect appears to work on Chrome Desktop Linux, Chrome Mobile Android, and Tor Desktop Linux.

On Brave desktop, if you type in without "https" it will say insecure; meanwhile if you explicitly type "https" it works fine. I've attached repro'd screenshots of all these cases.

I don't have an iOS device to test Brave mobile. I think this might be a Brave specific problem @zookozcash ? Either way I'll link to this issue to the provider and let them know.

![brave_no_https](https://user-images.githubusercontent.com/1434981/36634366-4d82a7dc-1958-11e8-9062-b1e1e59b46b4.png)
![brave_with_https](https://user-images.githubusercontent.com/1434981/36634367-4d9b8b44-1958-11e8-83e5-0da8fec12cdc.png)
![chrome desktop linux](https://user-images.githubusercontent.com/1434981/36634368-4db21832-1958-11e8-8a64-8cb4edfd3f26.png)
![chrome mobile android](https://user-images.githubusercontent.com/1434981/36634370-4dcda32c-1958-11e8-9669-9ea2257a6b57.png)
![tor_deskop](https://user-images.githubusercontent.com/1434981/36634371-4de580c8-1958-11e8-8356-1a8ef848a29d.png)

**Comment by zookozcash** [comment]
Confirmed that I can load it on Chrome on Chromebook.

**Comment by zookozcash** [comment]
Here's what the Qualys SSL server tester says:

https://www.ssllabs.com/ssltest/analyze.html?d=lists.z.cash.foundation&s=192.34.61.247

![screenshot 2018-02-24 at 21 15 37](https://user-images.githubusercontent.com/16416064/36635151-e20c8a22-19a7-11e8-9a78-f55f95be5906.png)

Nothing broken. I notice that it requires SNI support. Is it possible there's a bug in Brave's SNI support? /cc https://github.com/orgs/brave

**Comment by acityinohio** [comment]
Going to close this out—it appears to be something on Brave's end, thanks for checking.

**Comment by zookozcash** [comment]
I wanted to join the mailing list, but I don't see anything when I type "lists.z.cash.foundation" into Brave on iOS:

![6ca9ee6f-bdac-4bda-aba5-0866ee5f108a](https://user-images.githubusercontent.com/16416064/37247062-4a0b227e-246a-11e8-85f7-c5d8b80b150f.png)

So I typed it into Safari on iOS instead, and I got this error:

![e5140e89-ccf1-4819-ba15-3d02d2e93a75](https://user-images.githubusercontent.com/16416064/37247064-5ceb171e-246a-11e8-934d-d8675332edd3.png)

Then I tried Firefox Focus on iOS:

![9aa8143f-4ba6-482f-9392-d048be73e11a](https://user-images.githubusercontent.com/16416064/37247072-86108138-246a-11e8-852e-1e0b46d2a933.png)

Perhaps there's something about iOS, or about this particular phone that I'm trying this on?

**Comment by zookozcash** [comment]
Ok, I checked with an Android phone. It *works correctly* in Chrome on Android, but fails in Brave on Android or Firefox Focus on Android.

**Comment by amiller** [comment]
I couldn't reproduce the problem. I installed firefox focus and brave just now and the site loaded fine... Any other detail you could provide or ideas to check? Is there any chance you have modified ssl settings or certificate lists?

**Comment by mineZcash** [comment]
https://lists.z.cash.foundation/mailman/listinfo/zapps-wg try this link. 

It may be that you had http:// instead of https://

**Comment by zookozcash** [comment]
Ok, I clicked the link in Safari on iOS, and I get:



~\°»}.

**Comment by zookozcash** [comment]
> I couldn't reproduce the problem. I installed firefox focus and brave just now and the site loaded fine... Any other detail you could provide or ideas to check? Is there any chance you have modified ssl settings or certificate lists?
> 
I haven't intentionally modified any such settings.

Here is ssl labs client report for my Safari on iOS, which gives an (unspecified) ssl error:

**Comment by zookozcash** [comment]
Update! It now works with both Safari on iOS and Brave on iOS. I didn't change anything. Having thought about it for 5 seconds, I doubt there is any important residual security risk if we just all forget about this issue now, so I'm leaving this closed.
