### ISSUE TITLE
Operate or fund community operators of essential Zcash infrastructure.

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/ZcashFoundation#63]
Currently ZcashCo operates various kinds of Zcash infrastructure. Probably the most essential are seed nodes.

Ideally from my perspective ZcashCo would no operate any Zcash infrastructure in order to make Zcash resilient against the scenario of ZcashCo turning evil / imploding / being coerced, etc… The Foundation would be in a good position to define a set of "essential infrastructure" and then potentially fund its operation through grants.

IMO, the essential infrastructure includes:

- Seeder nodes, which help new nodes bootstrap into the network.
- Sufficient nodes to ensure the blockchain history is available to new nodes. (Ideally the network naturally provides this.)
- Hosting of zkSNARK parameters, which are necessary for using shielded transactions.
- Arguably: Nodes operating Tor hidden services and/or I2P equivalent, to enable IP address privacy.

Tangentially: I'm not clear if operating infrastructure or organizing and funding others to operate public infrastructure is within the mandate of the Foundation. Can we clarify this publicly?

**Comment by tromer** [comment]
Sounds like the right thing to do, except that for the "grants" part: resources with significant availability/confidentiality/integrity ramifications may need to be handled in-house by Foundation employees using Foundation-approved procedures. Or at least subcontracted to organizations with exceptional expertise and reputation, under terms that are much stricter than the Grants'.

**Comment by amiller** [comment]
Thanks for this issue, yes IMO all of these are within scope of what the Foundation should do operationally in-house. We should start by *replicating* each of these, then Zcash Co should turn *off* all of theirs for a while just to make sure it's working independently. Then later continue running theirs too.

**Comment by nathan-at-least** [comment]
I didn't realize the Foundation was on board for operating infrastructure directly. That works for me!

**Comment by zmanian** [comment]
If the Foundation is interested in subcontracting some infrastructure, @tarcieri and I have a infrastructure hosting venture that would be interested.

https://www.iqlusion.io/

**Comment by radix42** [comment]
Note that I currently operate one of the higher traffic (after Zcha.in) Zcash block explorers with Foundation grant support, and also host the proving key mirrored on a fast global CDN purely for donations, in addition to operating a number of high availability zcash nodes that allow inbound connections, so we're part-way there (FYI for those who may read this and not know it ahead of time, I am not nor have I ever been an employee of the Zerocash Electric Coin Company, aka ZcashCo or affiliated with it formally in any way).

**Comment by acityinohio** [comment]
[Closing this as part of a cleanup/consolidation to https://github.com/ZcashFoundation/zfnd]
