### ISSUE TITLE
Get the community's opinion on the next round of grants (Q2/Q4) + Other suggestions from outsider

### ISSUE THREAD

**Issue by ghost** [ZcashFoundation/ZcashFoundation#64]
Monero's FFS is super effective in getting users interested and engaged in the project. It's a pretty good filtering mechanism for high quality projects, and community also gives good feedback, mostly on Reddit.

I recognize that the grants are different, as the $$ comes from the foundation, but there is still an opportunity to increase community engagement and awareness in the foundation's activities.

I have 2 suggestions: 

- Implement an option where users can donate ZCash to any project proposal, in a format similar to the FFS. What are the downsides? 

- Somehow get user feedback. Most of the feedback on prior proposals is from the same small group of people on the ZCash team. Since it's the foundation's money, it makes sense that a small group of trusted people make final decision on where the $$ goes. However, even if the average user's opinion doesn't change the results (what gets funded), it will get them interested and thinking about the project.

Also: unrelated

- Why isn't Reddit leveraged more? It's an effective method of communication for crypto projects, but neither ZCash Co, nor the foundation link to it? The subreddit is pretty dead, and I think Dash and Monero's active subreddits contributes to their enormously active community. Reddit would be great way to get crowdsourced intelligence/feedback from non-technicals that[ Zooko complains about here. ](https://github.com/ZcashFoundation/ZcashFoundation/issues/58)

- Should you guys link to the ZCash chat on the foundation website? Like Zooko said, the average person is not going to click on repository, or even understand github. As a person new to ZCash, it's very difficult to navigate around and find the proper communication channels. Highly suggest exploring Reddit.

**Comment by ghost** [comment]
Also, am I allowed to just post issues/suggestions like this on this github lol ? I'm not too familiar with github ettiquete / rules

**Comment by amiller** [comment]
This is great feedback, thanks for writing it here hderek! 
The proposals being posted on GitHub makes them open for user feedback from anyone. But if not many people show up to comment, we should try additional things, I agree. We also have the foundation topic on forum.z.cash, do you think that is a good alternative to Reddit, or is the /r/zec subreddit the best place to proactively speak into?

**Comment by ghost** [comment]
> We also have the foundation topic on forum.zcash, do you think that is a good alternative to Reddit, or is the /r/zec subreddit the best place to proactively speak into?

Forum.zcash is a decent start, but I'm not sure I know too many Projects that have more lively/active proprietary forums compared to a Subreddit or something.  When newcomers are trying to learn about a project, one of the first places they will go is the Subreddit.

There are alot of downsides to Reddit, as the level of overall discourse will be lower, there's more talk of price, takes time to moderate, etc. However there will still be the occasional valuable and insightful comment/contribution.

It's the simplest way to get users from diverse backgrounds interested and contributing. You can easily create a small lively community with high quality contribution if there are good moderators who set the ground rules/are active.


-

**Comment by tromer** [comment]
@hderek, already in the 2017Q4 grant round, we were explicitly and actively seeking user input on grant proposals. As a member of the grant committee, I can say that we we gave a lot of weight to community feedback, and often reached out to people on other forums, and in person, to get more of it. If you have ideas on how to do more of that, they are _very_ welcome. Just bear in mind that practically we do need input to be gathered in some designated place (currently, the proposal's Github issues).

As I see it, a small grant review committee cannot experts in all grant areas, and may not be aware of all of the community needs and priorities. Thus, the ideal is for the committee to seek, curate and summarize community feedback and draw the conclusions on funding.

Facilitating project-specific donations is an excellent idea: to let people "put their ZEC where their mouth is" as evidence of importance, to get additional resources, and to foster excitement, engagement, and good will. Perhaps also to get money flowing faster than the formal process allows, if donations go directly to the projects without waiting for committee decisions.

**Comment by ghost** [comment]
Thanks for the response Eran!

> Just bear in mind that practically we do need input to be gathered in some designated place (currently, the proposal's Github issues).

I would say just keep getting the Github links to the proposals out there . Tweet them, post them to Reddit, have it visible on the home page of the foundation website, etc.

**Comment by acityinohio** [comment]
Thanks for the feedback again @hderek, closing this out as part of ZcF GitHub issues cleanup.
