### ISSUE TITLE
[Grant Program Request] Pipelined back-to-back grant rounds.

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/ZcashFoundation#69]
I'd like a "constantly available" grant program to direct potential applicants to. The number of potential applicants I notice is growing daily! It's exciting!

However, if there's no place where I can direct them that let's them know the next application deadline, we may be losing potential applicants who will drop off before the next round is set up and announced.

I don't think this "constant availability" needs to imply a fast pace or short turn-around time. Instead it needs to just ensure there is always a known deadline for "the next round".

That probably implies some reduced flexibility in changing anything between rounds since round `N + 1` must always be partially specified. If the grant round structure is fairly well known ahead of time, such as the CFP requirements and date, then "next round deadline" could be the CFP deadline itself.

If those parameters are not known ahead of time (or the Foundation wants to maintain more flexibility) then the deadline could be for the Foundation to announce the new CFP parameters. In that case, we should set up a way for applicants to register interest in the next round, such as a "sign up here for CFP announcements" mailing list.

See a related request to have a stable URL home for describing what the grant program is: https://github.com/ZcashFoundation/zcashfoundation.github.io/issues/27

**Comment by acityinohio** [comment]
Closing this out to summarize grant ideas in one issue, thanks @nathan-at-least!
