### ISSUE TITLE
[Grant Program Request] Continuation grants / lower barrier to repeat.

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/ZcashFoundation#70]
Some kinds of valuable Zcash projects may be ongoing processes rather than discrete projects, or they may be easily repeatable or extendable projects.

I've heard that the foundation has also considered funding ongoing projects outside of the grant program, such as by hiring contractors, or entering into custom agreements. Facilitating ongoing or continuous grant funding may be a nice middle ground that opens the doors to a wider variety of applicants and projects because the barriers to entry can be lower, while also allowing the Foundation to extend the existing Grant program thus saving overhead on their end, too.

Is there any way to lower the barriers to entry for grant projects of this nature? Some brainstorms are:

- Define some criteria for repeatable or ongoing process projects. One stab at this is if the project description, the budget, and the evaluation requirements for the grant reviewers are similar between rounds.
- Let first time applicants know that continuing or repeating projects is less effort in subsequent rounds.
- Ask applicants if their proposal is a repeatable / ongoing proposal.
- Ask returning applicants if their proposal is a repeatable/ongoing proposal that received funding in the previous round.
- In the grant acceptance process, consider returning repeat projects separately from first time or non-repeatable projects.
- In the grant milestone evaluation process, streamline evaluation of repeat projects.

A brainstorm about how to streamline the acceptance process for returning repeat/ongoing projects:

1. The acceptance process for repeat projects can be streamlined to first do a "changing priorities" check to see if a successful project in the previous round is no longer qualified due to changing grant program priorities due to no fault of the applicant.
2. If the priorities are still aligned, check if the previous round's milestone evaluations were all "green flags" (meaning no concerns and fully satisfied requirements). If so, immediately accept the new proposal under the same goals/scope/schedule/budget/conditions as last time.
3. If the previous round's milestone evaluations were "red" meaning the project had serious flaws such as incompetence, malice, recklessness, then immediately reject.
4. If the previous round's milestone evaluations were "yellow" meaning the project needed intervention, negotiation, or notably extra effort by the grant evaluators, then treat the application similar to a first-time application in which a more detailed proposal must be evaluated by the acceptance committee.

Likewise for milestone evaluations, repeat projects can be streamlined by cribbing from the previous evaluation framework.

**Comment by mineZcash** [comment]
I like this idea, the trick would be setting up a framework for these ongoing style submissions and having a quick/streamlined review process that has as few buy-offs as needed. 

Another thought, after seeing the quick turnaround of the ZenCash wallet port to Zcash via a Bounty posted by a ZenCash developer. It would be nice to have a similar Bounty style funding for a "very, very low" barrier to entry. 

I think it would encourage anonymous development work and Bounties also provide a sense of urgency to submit work since whoever submits the solution first can claim the Bounty. 

Drawbacks to a Bounty system may be a lack of IRS-able reporting information for winners which I'm not sure are compatible with a nonprofit organization.

**Comment by acityinohio** [comment]
Closing this out to summarize grant ideas in one issue, thanks @nathan-at-least!
