### ISSUE TITLE
Hire/contract for multiplatform Zcash Desktop Wallet GUI

### ISSUE THREAD

**Issue by acityinohio** [ZcashFoundation/ZcashFoundation#73]
Focused on post-Sapling, shielded TXs, currently interacting with zcashd.

**Comment by adityapk00** [comment]
Hello, I’m the developer of Zcash-qt-wallet, which is a multi platform desktop GUI wallet for Zcash. I’d be interested in this project. 

As you can see from my github, I’m already about halfway there. The GUI already supports windows and Linux, full support for sprout, sapling and t addresses. 

https://github.com/adityapk00/zcash-qt-wallet

How can I learn more about what you’re looking for?

**Comment by acityinohio** [comment]
This is fantastic @adityapk00. Do you mind emailing me at `josh [at] z [dot] cash [dot] foundation` and we can discuss a bit more?

**Comment by sonyamann** [comment]
We can close this issue now, no?
