### ISSUE TITLE
Hire protocol developer

### ISSUE THREAD

**Issue by acityinohio** [ZcashFoundation/ZcashFoundation#74]
# Job Opportunity: Protocol Developer and Open Source Maintainer

The Zcash Foundation is hiring a protocol developer and open source maintainer. Are you interested in furthering our mission of building Internet payment and privacy infrastructure for the public good, primarily through the Zcash? Do you have experience with Rust and C++ and familiarity with Bitcoin and Zcash at the protocol level? Do you want the freedom to work how you want, where you want, and on software that will _always_ be open source? Are you sick of all these rhetorical questions? Then (virtually) step right up!

## Requirements

- Proficiency with Rust and C++
- Familiarity with Bitcoin and Zcash protocols and codebases
- Experience maintaining open source projects and working with open source contributors
- Willingness to contribute to Zcash and to upstream projects
- Strong belief that financial privacy should be universally accessible

## Benefits

- Competitive salary, payable in USD and/or ZEC
- The Zcash Foundation is completely remote; work where and how you want
- Medical/Dental/401k benefits for US-based applicants
- Opportunity to shape engineering culture as first technical hire
- Mission >> Profit. We are a well-funded non-profit, which means you _never_ have to make technical compromises for the pursuit of short-term profit.

Interested? Send a resume/CV and any supporting links to `contact [at] z [dot] cash [dot] foundation` . We will endeavor to respond to every applicant.

**Comment by sonyamann** [comment]
Should we crosspost this as an issue in the new repo? Or maybe better to have a page on the website?

**Comment by acityinohio** [comment]
I think cross post as new issue for now, rather than set up a dedicated hiring page.

**Comment by acityinohio** [comment]
[Closing this as part of a cleanup/consolidation to https://github.com/ZcashFoundation/zfnd]
