### ISSUE TITLE
Polling Stakeholders

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#8]
Related to #4, except about polling stakeholders / coinholders instead of miners. These are potentially two different. Both might benefit from "representation" in the community, which the foundation could facilitate.

This feature issue from Zcash is closely related: https://github.com/zcash/zcash/issues/2321 The main idea is that the existing circuit could be used to approximate "stake" voting.

Decred has a really interesting voting system, overlaid on top of their proof-of-stake voting system. Only people who buy "voting tickets" by locking up their coins get to vote. Apparently today, 37% of their entire market cap is invested in voting tickets this way.
https://docs.decred.org/getting-started/user-guides/agenda-voting/

**Comment by acityinohio** [comment]
Closing this out with the success of the governance panel, although I do like the idea of re-purposing the circuit for staked voting in the future.
