### ISSUE TITLE
Community Survey

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#9]
We should have a working group for surveying community contributions for folks.
I think Zcash co had a post to this effect.
https://www.zcashcommunity.com/wallets/ this is a survey of wallets.
 What else should go here? Forks? Ports? Block explorers? Forums?

**Comment by mineZcash** [comment]
I try to keep an eye on the community contributions via the forums and Reddit and add them as I find them. I think its important that the community has links to as many resources as possible, I can add as many other pages as we need for forks, block explorers, etc.

**Comment by zancas** [comment]
If I Understand the survey task correctly, then I think ZEC supporting exchanges should be included.

**Comment by acityinohio** [comment]
Closing this issue since the first grant program selection has concluded, but this would be a good issue to support in the next round of grants.
